# Generated by Django 3.2.5 on 2021-08-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
